### ISSUE TITLE
dedupe crashes if one of the two files involved is busy

### ISSUE THREAD

**Issue by olifre** [markfasheh/duperemove#134] opened 2016-08-01 23:17 UTC
Consider:
```
# duperemove -d -r -h -v /home/olifre/.dropbox-dist/
- lots of chatter -
Removing overlapping extents
Simple read and compare of file data found 1 instances of extents that might benefit from deduplication.
Showing 2 identical extents with id f8b98459
Start           Length          Filename
0.0     23.2M   "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox"
0.0     23.2M   "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/library.zip"
Using 8 threads for dedupe phase
[0x1df1b20] Try to dedupe extents with id f8b98459
Error 26: Text file busy while opening "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox" (write=1)
/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox: Skipping dedupe.
[0x1df1b20] Add extent for file "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/library.zip" at offset 0.0 (3)
ERROR: run_dedupe.c:399
[stack trace follows]
duperemove(print_stack_trace+0x2b) [0x408a5b]
duperemove() [0x40b089]
duperemove() [0x40b460]
/usr/lib64/libglib-2.0.so.0(+0x70668) [0x7fbed15ab668]
/usr/lib64/libglib-2.0.so.0(+0x6fcd5) [0x7fbed15aacd5]
/lib64/libpthread.so.0(+0x7434) [0x7fbed0983434]
/lib64/libc.so.6(clone+0x6d) [0x7fbed0c8150d]
```
A short look with gdb shows the assertion:
https://github.com/markfasheh/duperemove/blob/master/run_dedupe.c#L399
fired. 
It seems we got there via:
https://github.com/markfasheh/duperemove/blob/master/run_dedupe.c#L335
which brought us back to the beginning of the loop even though `last=1` was already set. 
Like that, we reached the assert with a non-freed ctxt. 

Probably: 
https://github.com/markfasheh/duperemove/blob/master/run_dedupe.c#L335
should also check whether we are at `last` and exit in this case?

**Comment by markfasheh** [comment] 2016-08-01 23:47
Nice analysis, yeah this is an issue I believe I fixed today, see:

https://github.com/markfasheh/duperemove/issues/132

Would you mind trying the patch in 'issue#132' branch? I was not able to reproduce in my setup however it's clear to me what's going wrong.

https://github.com/markfasheh/duperemove/tree/issue%23132

I pulled in the fixes from master so you shouldn't be missing any patches.

**Comment by markfasheh** [comment] 2016-08-02 00:19
Marking as duplicate of #132

**Comment by olifre** [comment] 2016-08-02 02:27
Indeed, that's it! Not sure how I missed that issue report...
Now everything seems fine:
```
# duperemove -d -r -h -v /home/olifre/.dropbox-dist/
- lots of chatter -
Simple read and compare of file data found 1 instances of extents that might benefit from deduplication.
Showing 2 identical extents with id f8b98459
Start           Length          Filename
0.0     23.2M   "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox"
0.0     23.2M   "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/library.zip"
Using 8 threads for dedupe phase
[0x21da0a0] Try to dedupe extents with id f8b98459
Error 26: Text file busy while opening "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox" (write=1)
/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/dropbox: Skipping dedupe.
[0x21da0a0] Add extent for file "/home/olifre/.dropbox-dist/dropbox-lnx.x86_64-8.3.16/library.zip" at offset 0.0 (3)
Kernel processed data (excludes target files): 0.0
Comparison of extent info shows a net change in shared extents of: 0.0
```
Thanks a lot!

**Closed** 2016-08-04 23:10 UTC
Labels: duplicate
