### ISSUE TITLE
duperemove dedupe hangs on volume mounted with noatime option

### ISSUE THREAD

**Issue by dcartt** [markfasheh/duperemove#140] opened 2016-08-23 01:13 UTC
Running duperemove with the dedupe option on a volume mounted with the noatime option causes duperemove to hang.  It can't be killed and the system won't fully shut down on its own (requires a hard power off).  This only happens if duperemove finds some minimal amount of deduplication to do.  In other words, if duperemove finds nothing or only a few things to dedupe then it doesn't hang.  Running duperemove with just the find option never hangs.

duperemove v0.11.beta1
btrfs-progs v4.7
4.7.0 kernel, x64

The noatime mount option appears to be necessary to cause the hang.  It doesn't hang with the relatime mount option or with no mount option instead.

The attached "dmesg.hung-tasks.txt" has the output from dmesg after duperemove had been hung for a long time.  Unfortunately I don't have a copy of the console output at the point it had hung.  I do have all that output up to a point just a bit before the hang, and the full output of a duperemove find done just before.  It's easily repeatable though.  Happy to supply more info or run additional tests.

[dmesg.hung-tasks.txt](https://github.com/markfasheh/duperemove/files/431466/dmesg.hung-tasks.txt)

**Comment by markfasheh** [comment] 2016-08-25 20:22
Thanks very much for the detailed bug report. The hung tasks in particular is perfect.

I hit a very similar issue during some of my testing about 2 weeks ago. In my case there was a deadlock with btrfs transaction thread and btrfs fiemap. They ABBA deadlock the commit_root_sem and the tree_lock.

What you gave me from dmesg looks almost exactly like what I got except I don't have the transaction thread here so I can't be 100% sure. In particular, all the threads sitting on btrfs_read_tree_lock() is exactly what I had.

This is on my very short list of kernel bugs to fix as people are already hitting it and it's blocked some of my own duperemove testing.

If you don't mind reproducing it again and doing 'echo t > /proc/sysrq-trigger' when it hits I could narrow it down further to exactly my issue (or not).

Btw, does it still seem tied to noatime for you? I didn't find any such correlation however I didn't test for that specifically.

**Comment by dcartt** [comment] 2016-08-26 05:46
I re-ran the test and it worked when it should have failed.  But I'd changed the test script a little bit, adding a btrfs-filesystem-sync before each unmount and a btrfs-scrub after each mount.  These are both done after setting up the test data on the btrfs file system and just before doing the Duperemove dedupe.  Commenting out both the sync and scrub resulted in the dedupe hanging again.

Also tested with different mount options.  Summary: always hangs with noatime, no sync, and no scrub, and always succeeds with either no noatime or both sync and scrub.  With the noatime option I'm not seeing 100% consistency when doing either a sync or a scrub, but (so far!) doing both a sync and scrub always succeeds and doing neither a sync or scrub always fails.  With no mount option, doing neither sync or scrub succeeds.  I tested both noatime and compress=lzo and the result were roughly the same.  

Here's the table of results in case the above doesn't make sense:

Duperemove dedupe hang conditions:

Mount option: noatime

fails: 
* no sync, no scrub

works: 
* no sync, scrub
* sync, scrub

sometimes works/fails:
* sync, no scrub

Mount option: noatime,compress=lzo

fails:
* no sync, no scrub
* sync, no scrub

works:
* no sync, scrub
* sync, scrub

Mount option: none

works:
* no sync, no scrub


I did the sysrq-trigger you asked for.  The full output of the run is attached in the file "BTRFS_nocrypto.noatime-compress-lzo.4.output.txt".  The output of some commands are redirected to their own files and therefore don't appear in this file.  For example, the Duperemove find and dedupe commands.  Most of the script was run with "set -x" so any line beginning with a plus is a command.  All other lines are stdout+stderr.  A few key points:
* Line 46: btrfs file system created.
* Line 68 and 102: File system mounted.  Between those two mounts is where the test data is copied over and the file names obfuscated.  A btrfs-check with no repair is also done there.
* Line 136: Duperemove with no dedupe (find) done.  stdout+stderr redirected to a file.
* Line 141: Duperemove with dedupe done.  stdout+stderr redirected to a file.  This is the last line of the file, where it hangs.

The sysrq-trigger output along with the "blocked for more than 120 seconds" messages are in the file "BTRFS_nocrypto.noatime-compress-lzo.4.dmesg.hung-tasks.tar.gz".



[BTRFS_nocrypto.noatime-compress-lzo.4.output.txt](https://github.com/markfasheh/duperemove/files/438557/BTRFS_nocrypto.noatime-compress-lzo.4.output.txt)
[BTRFS_nocrypto.noatime-compress-lzo.4.dmesg.hung-tasks.tar.gz](https://github.com/markfasheh/duperemove/files/438560/BTRFS_nocrypto.noatime-compress-lzo.4.dmesg.hung-tasks.tar.gz)

**Comment by markfasheh** [comment] 2016-09-07 03:47
Could I trouble you to test with this branch:

https://github.com/markfasheh/duperemove/tree/no-fiemap

It disables fiemap usage in duperemove. I want to see if we can rule it out (or in) as one part of the problem. If you get hangs, give me the same info you have been - sysrq-t being the most important.

Thanks.

**Comment by dcartt** [comment] 2016-09-09 01:31
The no-fiemap branch does not hang.  I used "-o noatime" mount option and no syncs or scrubs for all tests.

I ran the test with the v0.11.beta1 code that I've been using all along just to make sure it still hangs.  It does.  Then ran the same test with the no-fiemap code.  No hang.  Then ran the same test with the current master code.  That hangs too.

**Comment by markfasheh** [comment] 2016-09-21 23:02
Closing for now thanks again for reporting this.

For anyone who might hit this in the future, use --dedupe-options=nofiemap and --lookup-extents=no to completely disable fiemap usage in duperemove.

**Closed by markfasheh** 2016-09-21 23:02 UTC
