### ISSUE TITLE
Output buffer causes empty "log" when running on big files in background

### ISSUE THREAD

**Issue by EdoaLive** [markfasheh/duperemove#63] opened 2015-05-14 09:53 UTC
Hi all
I was trying deduperemove on very big files. I use nohup tool to launch long tasks so I can close the terminal without interrupting the task. Then I check nohup.out (where stdout and stderr are redirected by default) from time to time to check the progress.
In case of duperemove, this file contains just the stderr (e.g. `Warning: murmur3 support is experimental!`) but not the verbose log that I usually see in my terminal, at least not in a long time.
The issue doesn't present if I run duperemove in a little folder with little files.

I found this workaround:
`stdbuf -i0 -o0 -e0 ./duperemove --hashfile=hashes.file -dAv [...] > log.txt`
But I think we should flush standard output buffer every line or from time to time...

**Comment by markfasheh** [comment] 2015-05-14 18:03
Just to be clear - you eventually *do* get the output, but it's delayed a long time due to buffering? Or are you saying you never get stdout (which would be puzzling to say the least).

**Comment by Edoa** [comment] 2015-05-15 09:12
I presume the first you said. 
I tried on smaller files: at the end of the execution the output log is complete (with stderr first, then the stdout) see: http://pastebin.com/CrDJwn4D. 
At this time I don't have a "right" size file to tell if the stdout is actually written after some time OR just at the end of execution OR after a certain time.
I usually use ```tail -f nohup.out``` to follow the output file during the execution.

**Comment by markfasheh** [comment] 2015-05-15 18:43
Ok so we can just flush our output buffers at some points in the code. My guess is that you're probably seeing this during the csum phase because that's when we print the most stuff.

**Comment by markfasheh** [comment] 2015-05-28 23:10
Would you mind trying  the 'fflush' branch of duperemove.git? It adds a patch to make this less of an issue.

**Comment by markfasheh** [comment] 2015-06-17 21:33
Merged this, we'll just test it in master.

**Comment by Edoa** [comment] 2015-06-29 15:33
Sorry for the late reply.
I'm sorry but if the modifies have been merged in master branch, the problem still occurs.

Express footage:
```console
duperemove-master # nohup nice ionice -c3 ./duperemove --hashfile=file.hash -d /mnt/2TB_snap.iscsi /mnt/old/m/2015-06-28_17-24-01/2TB_snap.iscsi /mnt/old//m/20
15-06-22_17-18-01/FILENORME.vhdx /mnt/nosnap/nosnap.iscsi &
[1] 4102
nohup: ignoring input and appending output to 'nohup.out'
[...]
duperemove-master # tail -f nohup.out
Warning: murmur3 support is experimental!
^C
```
Correct behavior without nohup:
```console
duperemove-master # nice ionice -c3 ./duperemove --hashfile=file.hash -d /mnt/2TB_snap.iscsi /mnt/old/m/2015-06-28_17-24-01/2TB_snap.iscsi /mnt/old//m/2015-06-22_17-18-01/FILENORME.vhdx /mnt/nosnap/nosnap.iscsi
Warning: murmur3 support is experimental!
Using 128K blocks
Using hash: murmur3
Using 2 threads for file hashing phase
csum: /mnt/2TB_snap.iscsi       [1/4] (25.00%)
csum: /mnt/old/m/2015-06-28_17-24-01/2TB_snap.iscsi     [2/4] (50.00%)
^C
```

**Comment by markfasheh** [comment] 2015-07-02 06:42
Go ahead and try master branch again, I made a change earlier today to help this out though I think it may need more work.

**Comment by Edoa** [comment] 2015-07-03 10:27
Still nothing, except for the `Warning: murmur3 support is experimental!` not appearing anymore.
Just out of curiosity, could any of you reproduce this problem?

**Comment by markfasheh** [comment] 2015-07-03 16:44
Oh yeah this happens to me on my long run. The most annoying thing was that the software would be deduping but the output would still show at the csum stage. My patch above fixes that however it doesn't fix the problem where we might get a bunch of output queued at the csum stage *before* it completes. For that I think we just need to flush every N files or T seconds. The problem is finding a value for those which helps but doesn't hose the program performance. I really haven't had time to experiment in that area yet.

I'm not using the nohup progam though, just piping to a file. Maybe it's worse there for some reason? I see that you're only doing like 2-4 files when this happens? That's pretty extreme.

**Comment by Edoa** [comment] 2015-09-11 14:43
> I'm not using the nohup progam though, just piping to a file. Maybe it's worse there for some reason?
I don't think so. Maybe it's worse because of the low number of files.

>I see that you're only doing like 2-4 files when this happens? That's pretty extreme.
Those files are some iSCSI disk images. I've read that duperemove is not optimal on Disk images, but if it worked good, it would be very effective on this kind of data (most parts of the operating system files are the same in different VMs disks).

**Comment by ivanbaldo** [comment] 2019-05-23 21:15
I think duperemove should use line buffering as every other program to avoid surprises.
Do you have numbers that show too much of a slowdown if you use line buffering?
Otherwise its a silly optimization that just causes trouble and more work for users.
Thanks!!!

**Comment by JackSlateur** [comment] 2023-09-20 17:47
Hello,

Some years later, I have checked and implemented line-based buffering
I believe this issue is fixed, please feel free to reopen it if needed

**Closed by JackSlateur** 2023-09-20 17:47 UTC
