### ISSUE TITLE
duperemove-dev fails to find duplicates (0.11.1 works though)

### ISSUE THREAD

**Issue by matthiaskrgr** [markfasheh/duperemove#224] opened 2019-10-28 21:09 UTC
I was checking my entire disk and duperemove was not able to dedupe anything which seemed suspicious.

I tried out `cat bigfile > copy; duperemove .` but duperemove did not dedupe anything
````
Total files:  5
Total extent hashes: 0
Loading only duplicated hashes from hashfile.
Found 0 identical extents.
Simple read and compare of file data found 0 instances of extents that might benefit from deduplication.
Nothing to dedupe.
````
so I'm wondering if it is still working. :/

edit: I'm on linux 5.3.7 / btrfs-progs v5.3

**Comment by Palando** [comment] 2019-11-04 09:13
For me it also does not work anymore. I'm using xfsprogs 5.0.0-1.4 and linux 5.3.7-1 on OpenSUSE. It found 0 identical extents but before I copied a file.

**Comment by dominikholler** [comment] 2019-11-04 09:27
While the current master branch does not work for me, v0.11.1 works on CentOS 8 for me.

**Comment by Palando** [comment] 2019-11-04 09:53
Ah, yes. For me too. I just gave it a try. Thank you!

**Comment by tux3** [comment] 2019-11-09 20:44
I just ran into this issue on master. I've only glanced at the code but I think this might be because the last commit (128acd99fc4ff1c6735083ffd69951ba9d7c997e) causes `csum_extent` to return 0 when `csum_by_block`/`csum_by_extent` still interpret 0 as EOF, so it just gives up on each file after trying the first extent..

**Comment by beh666** [comment] 2019-12-07 03:01
I can confirm this issue still persists using the latest master. Using kernel v5.4.2 and xfsprogs v5.2.1,

**Comment by warthog9** [comment] 2019-12-27 06:23
Quick bisect, c61a144a5f0c0a546a31340808bab122c58b2306 is where this stops working on dev likely (at least for me)

**Comment by warthog9** [comment] 2019-12-27 06:25
Also noting this is where dev has --dedupe-options= which is likely what you are seeing as a bug, this may just be a miss-understanding of the new options

**Comment by beh666** [comment] 2019-12-29 16:38
If so, what would be the proper way to use the tool in order to duplicate (no pun intended) the previous behaviour?

**Comment by jfikar** [comment] 2020-02-18 13:00
I think it should be `--dedupe-options=partial,same` but it does not work. See #216

**Comment by zhangboyang** [comment] 2020-03-27 16:26
I have encountered the same problem.

**Comment by Leicas** [comment] 2020-06-01 20:14
Same issue for me.

**Comment by lorddoskias** [comment] 2020-07-07 14:00
Can you retest latest code in master. I believe this should be fixed by 30e5c7a7fd502d55069977f2037b2c26a3aff684

**Comment by matthiaskrgr** [comment] 2020-07-08 12:14
Looks like its working again :)

**Comment by lorddoskias** [comment] 2020-07-08 12:17
In this case I will close this issue if there are anymore problems keep reporting them!

**Closed by lorddoskias** 2020-07-08 12:17 UTC
