### ISSUE TITLE
OOM-killed even with --hashfile

### ISSUE THREAD

**Issue by unhammer** [markfasheh/duperemove#118] opened 2016-04-14 07:05 UTC
I did 
`$ sudo duperemove -dhr --hashfile=$HOME/.cache/duperemove.deleteme  /mnt/edbb9e0d-4a65-4178-b66d-b633aefe4cb2/ ` 
(that's a 3TB USB drive), but $HOME/.cache/duperemove.deleteme is never created, and duperemove is OOM-killed. 
```
[245454.306446] Out of memory: Kill process 6245 (duperemove) score 814 or sacrifice child
[245454.306451] Killed process 6245 (duperemove) total-vm:7294900kB, anon-rss:2955640kB, file-rss:0kB
```

This is with duperemove 0.10-2 from https://aur.archlinux.org/packages/duperemove/ 

Is there something wrong in how I'm invoking duperemove, or is it running out of memory before the hashfile-step? 

EDIT: seems to be the latter – if I select a subdirectory of the drive, it only goes up to 75% mem and the hashfile is created and it seems to run fine.

**Comment by ikrabbe** [comment] 2016-06-23 09:39
Generally spoken: duperemove does definately use too much space. I did not check the code yet, but 2.5GByte to compare hashes and fire system calls against btrfs just "feels" far to big.

**Comment by ikrabbe** [comment] 2016-06-23 09:41
Ups, this is a duplicate of https://github.com/markfasheh/duperemove/issues/116

**Comment by clobrother** [comment] 2016-06-23 09:42
Many improvements are made some times, please use the last code from master, it should be better from that point of view (still work to be done, but ..)

**Comment by markfasheh** [comment] 2016-08-04 23:40
Regarding memory usage I'm going to run a couple of tests now with extra mem stats to see if anything comes up as out of the ordinary. It will also give me a couple of data points to work from when we talk about relative usage of various structures within the code.

**Comment by markfasheh** [comment] 2016-08-07 02:42
Ok, the biggest user of memory is the results tree. This is storing duplicated extents in buckets for later dedupe. The dupe extent finding code throws quite a few candidates at us and each one adds up and we peak in memory usage during that stage. For example, on a 900G test file system filled with files that are mostly zeros, the code found upwards of 2 million extents. The good news is that we then prune the tree down quite a  bit so the memory usage is temporary.

That said, I'm working on a patch to do some of that pruning as we try to insert items into the tree. We still have to run them afterwards but what I'm seeing now is promising (about 50% reduction in total number of allocated extents). There's also other approaches - struct extent in the code could be trimmed down a little bit. There are some fields which are only used during the dedupe stage where generally we have plenty of memory. It might be good to put those fields in a dynamically allocated structure that is attached to the extent only for the duration of a dedupe pass.

Is anyone willing to give these changes a spin once I put them in a topic branch? (maybe a day or two from now). Mostly I want to ensure that we are deduping the same or about the same amount of data at the end of the process  as we were before.

**Comment by lapsio** [comment] 2016-09-20 15:24
ZFS for deduplication can eat even like 128gb of ram on storage servers lol. Just some rough estimation from one site: 

> Example: If a zpool stores 5 TB of data at an average block size of 64K, then 5TB divided by 64K yields 78125000 blocks. Multiplied by 320 Bytes, we get a dedup table size of 25 GB!
>
> RAM Rules of Thumb
>
> If this is all too complicated for you, then let's try to find a few rules of thumb:
>
> For every TB of pool data, you should expect 5 GB of dedup table data, assuming an average block size of 64K.

btrfs and dedupe seem be **really** good with RAM usage.

**Comment by markfasheh** [comment] 2016-09-27 20:22
Ok, the man page has information in the FAQ section about how much memory we might use (based on the size of a single block hash structure). Also we're doing block dedupe by default now so that should cut out the extremely memory hungry find-dupes step unless a user wants to run with that.

Btw, I mis spoke about the results-tree, it gets big but the biggest user is actually the file comparison tracking structure. Taking the compare tracking out helps the memory situation a ton but consumes at least 25% more cpu (and worse, even more than that when the # of files grows).

**Closed by markfasheh** 2016-09-27 20:22 UTC
