### ISSUE TITLE
why is nothing getting deduped

### ISSUE THREAD

**Issue by mac-linux-free** [markfasheh/duperemove#55] opened 2015-04-06 21:58 UTC
Kernel processed data (excludes target files): 49.6G
Comparison of extent info shows a net change in shared extents of: 0.0

with bedup i had 20gb of recovered space.

what could i do ?

**Comment by markfasheh** [comment] 2015-04-07 21:46
I'm getting the same thing, on my end it looks like the estimate done for shared extents is going wrong somehow. If you use the show-shared-extents program on a file which was supposed to be deduped you should see some of the extents as shared, which would indicate success. I'll update once I have an idea what's going wrong in duperemove.

**Comment by markfasheh** [comment] 2015-04-08 23:05
what kernel are you running? Btrfs on my 3.19 and 3.18 kernels are always reporting extents as shared, which I believe to be a bug.

**Comment by mac-linux-free** [comment] 2015-04-09 09:14
yes on my system kernel 3.19.3 is running with btrfs-progs 3.19.1

**Comment by markfasheh** [comment] 2015-04-09 20:02
Yeah so I can confirm that fiemap is broken in btrfs from 3.18 and onward - it is reporting shared extents when they are not actually shared. That messes up the estimate duperemove does on change in shared space (we fiemap before and after a dedupe to see how many bytes changed).

You can either roll back to 3.17 or wait until I get a fix out. In the meantime assume the space reporting is broken due to the above issue, but duperemove seems to be doing the right thing.

**Comment by mac-linux-free** [comment] 2015-04-09 20:19
thank you very much ... i wait :)

**Comment by dominicraf** [comment] 2015-04-12 14:29
This may explain my experience too (different issue report) - although I also found that the estimated free space reported by `btrfs fi usage` didn't increase after using `duperemove`. Still, will look forward to the updated `duperemove`...

**Comment by mac-linux-free** [comment] 2015-04-15 19:50
same with kernel 4.0.0

**Comment by markfasheh** [comment] 2015-04-21 22:55
I sent a patch out to the btrfs list regarding this today.

http://permalink.gmane.org/gmane.comp.file-systems.btrfs/44579

So hopefully this will get sorted out upstream at least. If it is accepted I will ask that it be backported to 3.18 and up.

**Comment by mac-linux-free** [comment] 2015-05-08 19:50
kernel 4.0.2 many btrfs patches...but issue not solved

**Comment by markfasheh** [comment] 2015-05-22 20:03
Ok, there's two bugs at play here. The first one, regarding btrfs fiemap being broken on kernels 3.18+ is solved by the patch I posted in my previous comment and again tot he btrfs list this week:

http://article.gmane.org/gmane.comp.file-systems.btrfs/45282/match=clear+ret+btrfs_check_shared

We're just waiting on it to be included in the kernel and backported to -stable. From there your distro will have to pick it up. If you build your own kernel things are faster - you can just grab the patch from my e-mail and apply it.

The other bug is detailed in issue#51 and I believe that you suffer from it as well. Fixing it is a work in progress. I'm going to close this bug since I have a patch upstream for it and ask that you follow / comment on issue #51 for the 2nd fix.

Thanks

**Closed by markfasheh** 2015-05-22 20:03 UTC

**Comment by mac-linux-free** [comment] 2015-06-28 19:46
does someone know if this is fixed now in kernel 4.1 and btrfs-progs 4.1?

I have different results, for me it is working if i create a new btrfs pool. But after 2 rsync´s --inplace it dedupes again nothing.

**Comment by markfasheh** [comment] 2015-06-30 01:08
The fiemap fix should be in 4.1.

The other fixes are on the btrfs mailing list - see issue#51 for a status there. If you feel you have a problem that isn't covered by either of these, let me know.
