### ISSUE TITLE
Effects of -A option on read/write enabled subvolumes?

### ISSUE THREAD

**Issue by Claes1981** [markfasheh/duperemove#86] opened 2015-07-12 13:36 UTC
Hi,

I have a question about the "-A" option of Duperemove. According to the manual it "Opens files readonly when deduping. Primarily for use by privileged users on readonly snapshots." It seems like you have to use this option if you want to dedupe readonly snapshots.

Are there any difference in the result or effects on the files of read/write enabled subvolumes when running Duperemove with the "-A" option, versus running Duperemove without the "-A" option? (For example dedupe over both read/write enabled /subvolumeA and readonly /subvolumeA/.snapshots/snapshot1.)

If there are no difference in the results, why are files not always open readonly when deduping? (No need of an "-A" option.) Perhaps is it slower?

**Comment by markfasheh** [comment] 2016-10-14 20:34
Hi this is because the kernel will only allow dedupe of files open for read if you are the root user, so by default we open for write. On a readonly snapshot though, this can be a problem so -A forces duperemove to always open for read.

**Comment by markfasheh** [comment] 2016-10-14 20:40
There's more detail on the problem in <https://github.com/markfasheh/duperemove/issues/129>, I'm going to close this issue and keep that one open until we have a resolution. Thanks.

**Closed by markfasheh** 2016-10-14 20:40 UTC
